// <auto-generated />
namespace MustDo.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UniaoDataHoraTarefa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniaoDataHoraTarefa));
        
        string IMigrationMetadata.Id
        {
            get { return "201703272045387_Uniao-DataHora-Tarefa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
